name: Test
on: [push]
jobs:
  test:
    name: incus-test-with-almalinux
    runs-on: ubuntu-latest
    steps:
      - name: Stop and Unsintall Docker
        run: |
          sudo systemctl stop docker
          sudo systemctl disable docker
          sudo apt remove --auto-remove -y docker-ce
          sudo rm -rf /usr/libexec/docker
          sudo rm -rf /etc/docker
          sudo apt purge --auto-remove -y docker-ce
          sudo apt clean
      - name: Reset Network
        run: |
          sudo systemctl restart systemd-networkd
      - name: Reset the firewall
        run: |
          sudo nft list ruleset
          sudo nft flush ruleset
      - name: Install Incus
        run: |
          sudo apt update
          # We can use the official Ubuntu APT repository when
          # ubuntu-latest is Ubuntu 24.04.
          sudo curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
          cat <<SOURCES | sudo tee /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
          Components: main
          Architectures: $(dpkg --print-architecture)
          Signed-By: /etc/apt/keyrings/zabbly.asc
          SOURCES

          sudo apt update
          sudo apt install -y -V incus
      - name: Access the external network on AlmaLinux using incus
        run: |
          sudo incus admin init --auto
          sudo incus launch images:almalinux/8 target
          sleep 10
          sudo incus exec target -- sudo dnf update -y
          sudo incus stop target
          sudo incus delete target
